# Service for DeepLearning backend interface with ROS system (sensor_msgs/Image, threshold_param) -> detections
sensor_msgs/Image image # the image to run the backend detector on
---
rasberry_perception/ServiceStatus status # the job completion status
rasberry_perception/Detections results # the corresponding detections