# Service for DeepLearning backend interface with ROS system (sensor_msgs/Image, threshold_param) -> detections
sensor_msgs/Image image
---
rasberry_perception/DetectionStatus status
rasberry_perception/Detections detections